/** Curated suggestions for profile skills autocomplete (freeSolo allows any custom tag). */
export const SUGGESTED_SKILLS = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "Go",
  "Rust",
  "C#",
  "C++",
  "Ruby",
  "PHP",
  "Swift",
  "Kotlin",
  "React",
  "Next.js",
  "Vue.js",
  "Angular",
  "Svelte",
  "Node.js",
  "Express",
  "GraphQL",
  "REST API",
  "HTML",
  "CSS",
  "Tailwind CSS",
  "SASS",
  "Redux",
  "Zustand",
  "React Query",
  "Webpack",
  "Vite",
  "PostgreSQL",
  "MySQL",
  "MongoDB",
  "Redis",
  "Prisma",
  "DynamoDB",
  "Elasticsearch",
  "AWS",
  "Google Cloud",
  "Azure",
  "Docker",
  "Kubernetes",
  "Terraform",
  "CI/CD",
  "Git",
  "Linux",
  "Microservices",
  "System design",
  "Machine learning",
  "Data analysis",
  "SQL",
  "Product management",
  "Agile",
  "Scrum",
  "Figma",
  "UI/UX design",
  "Technical writing",
  "Leadership",
  "Communication",
  "Spring Boot",
  ".NET",
  "Django",
  "Flask",
  "FastAPI",
  "Rails",
  "Laravel",
  "Playwright",
  "Jest",
  "Cypress",
  "Salesforce",
  "SAP",
  "Excel",
  "Power BI",
  "Tableau"
].sort((a, b) => a.localeCompare(b));
